package com.icefek.models.notentity;

public enum MenuType {
    USER_MAIN,
    USER_GET,
    USER_CREATE,USER_CREATE_DESCRIPTION,USER_CREATE_STATUS,USER_CREATE_SUCCESS,USER_CREATE_UNSUCCESS,
    USER_DELETE,USER_DELETE_SUCCESS,USER_DELETE_UNSUCCESS,
    USER_UPDATE,USER_UPDATE_DESCRIPTION,USER_UPDATE_STATUS,USER_UPDATE_SUCCESS,USER_UPDATE_UNSUCCESS,

}
